source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!


target :XLReactiveCocoaExtensionsDev do
  pod 'XLReactiveCocoaExtensions', :path => './../'
end

target :XLReactiveCocoaExtensionsDevTests do
  pod 'XLReactiveCocoaExtensions', :path => './../'
  pod 'Specta', '~> 1.0'
  pod 'Nimble', '~> 5.1', :inhibit_warnings => true
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
